---
- name: update servers
  apt: 
    name: "*"
    state: latest
  when: ansible_facts['distribution'] == "Debian" and sequence == 'wave_1'

- name: reboot 
  reboot:
  when: sequence == 'wave_1'

- name: update hypervisor
  apt: 
    name: "*"
    state: latest
  when: sequence == 'wave_2'

- name: reboot 
  reboot:
    post_reboot_delay: 60
    reboot_timeout: 1200
  when: sequence == 'wave_2'
