---
- name: Patching and Custom Tasks
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Upgrade all packages
      apt:
        upgrade: dist
      when: ansible_os_family == 'Debian'

    # Add your additional tasks here

    - name: Reboot if required after patching
      reboot_timeout: 60  # Delay of 1 minute (in seconds)
      ignore_errors: yes
      when: ansible_reboot_required

    - name: Wait for the server to come back
      wait_for_connection:
        delay: 60
        timeout: 300
      when: ansible_reboot_required
