---
- name: Rotate root password playbook
  hosts: all
  become: yes
  gather_facts: no
  vars_prompt:
    - name: new_root_password
      prompt: "Enter new root password: "
      confirm: true
      private: no
      
  tasks:
    - name: Change password for root
      user:
        name: root
        password: "{{ new_root_password | password_hash('sha512') }}"

