- name: create snapshot
  hosts: all
  vars_files:
    - vars.yaml
  tasks:
  - name: Create new container snapshot
    community.general.proxmox_snap:
      api_user: "{{ api_user }}"
      api_password: "{{ api_password }}"
      api_host: "{{ api_host }}"
      vmid: "{{ vmid }}"
      state: present
      snapname: test-snap
